# https://taskfile.dev

version: '3'
silent: true
# Can't be set in the included taskfile.
dotenv: [database/settings.env]
includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app
  db:
    taskfile: ./database/Taskfile.yml
    dir: ./database
tasks:
  ports:
    cmds:
      - lsof -nP -iTCP -sTCP:LISTEN
