env: dev

database:
  jdbcUrl: "${JDBC_URL}"
  username: "${JDBC_USERNAME}"
  password: "${JDBC_PASSWORD}"
  maximumPoolSize: 1

server:
  host: 0.0.0.0
  port: 8686
  # The working directory will be different (by default) depending on whether it is run from Gradle or IDEA.
  static: "browser/build/distributions/"
