appEnv: DEMO

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/demo"
  username: "username"
  password: "password"
  maximumPoolSize: 4

server:
  host: localhost
  port: 8686
  session:
    domain: "localhost"
    maxAgeInSeconds: 3600000
    signingKey: "aac4130eb7cfcd23263b1d5e11e11383"
    encryptionKey: "128467d75bea8372dad6252091de57d9"
  static: "app/browser/main/build/dist/js/productionExecutable"
