appEnv: demo

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/demo"
  username: "username"
  password: "password"
  maximumPoolSize: 1

server:
  host: 0.0.0.0
  port: 8686
  static: "browser/build/distributions/"
