appEnv: demo

database:
  jdbcUrl: "jdbc:postgresql://localhost:8687/demo"
  username: "username"
  password: "password"
  maximumPoolSize: 4

server:
  host: 0.0.0.0
  port: 8686
  static: "app/browser/build/distributions/"
