env: demo

database:
  jdbcUrl: "jdbc:postgresql://demo_pg:5432/demo"
  username: "username"
  password: "password"
  maximumPoolSize: 1

server:
  host: 0.0.0.0
  port: 8686
  # The working directory will be different (by default) depending on whether it is run from Gradle or IDEA.
  static: "browser/build/distributions/"
